services:
  app:
    volumes:
      - .:/app:ro,z
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
            - logs/
            - Dockerfile
            - docker-compose.yml
        - action: rebuild
          path: package.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: .env
