services:
  app:
    build:
      context: .
      cache_from:
        - docker-node-image
    image: docker-node-image
    container_name: docker-node-server
    command: yarn server
    env_file:
      - .env
    ports:
      - "${LOCAL_PORT:-5000}:${CONTAINER_PORT:-5000}"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: always
